/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.10-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.razr.coding.exercise.api;

import java.net.URI;
import java.net.URISyntaxException;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import com.fasterxml.jackson.annotation.JsonView;
import com.razr.coding.exercise.model.Square;
import com.razr.coding.exercise.model.Views;
import com.razr.coding.exercise.repo.ShapeRepository;

@RestController
public class SquareController {

	@Autowired
	ShapeRepository shapeRepository;
	
    @GetMapping(value = "/squares/{sideLength}",
    produces = { "application/json" })
    public ResponseEntity<Square> getSquareByRadius(@PathVariable("sideLength") Double sideLength) {
    	Square square = shapeRepository.getSquare(sideLength);
    	if( square != null ) {
    		return new ResponseEntity<Square>(square, HttpStatus.OK);
    	}
    	else {
    		return ResponseEntity.notFound().build();
    	}
    }

    @PostMapping(value = "/square",
    consumes = { "application/json" },
    produces = { "application/json" })
    @JsonView(Views.Create.class)
    public ResponseEntity createSquare(@RequestBody @JsonView(Views.Create.class) Square square) throws URISyntaxException {
        shapeRepository.addSquare(square);
        return ResponseEntity.created(new URI("/square/" + square.getSideLength())).build();
    }

    @DeleteMapping(value = "/squares/{sideLength}",
    produces = { "application/json" })
    public ResponseEntity deleteSquare(@PathVariable("sideLength") Double sideLength) throws URISyntaxException {
    	Square square = shapeRepository.deleteSquare(sideLength);
    	if( square != null ) {
    		return ResponseEntity.ok().build();
    	}
    	else {
    		return ResponseEntity.notFound().build();
    	}
    }
}